export type CasteEntry = { name: string; category: string; nigama: string };

export const CASTES: readonly CasteEntry[] = [
  { name: "Ganiga - ಗಾಣಿಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Teli - ತೇಲಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Gandla - ಗಾಂಡ್ಲ", category: "2A", nigama: "Devraj Urs" },
  { name: "Vaniyan - ವನಿಯನ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Jyothi Nagar/Jyothi Nagar Vyshya - ಜ್ಯೋತಿನಗರ/ಜ್ಯೋತಿನಗರ ವ್ಯಶ್ಯ", category: "2A", nigama: "Devraj Urs" },
  { name: "Ediga - ಈಡಿಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Bandhari - ಬಂಧಾರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Belbad - ಬೆಲ್ಬದ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Billava - ಬಿಲ್ಲವ", category: "2A", nigama: "Devraj Urs" },
  { name: "Pujari - ಪೂಜಾರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Divara - ದೀವರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Hala Kshatriya - ಹಾಲ ಕ್ಷತ್ರಿಯ", category: "2A", nigama: "Devraj Urs" },
  { name: "Desh Bhandari - ದೇಶ ಭಂಡಾರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Devara - ದೇವರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Devara Makkalu / Deevara Makkalu - ದೇವರ ಮಕ್ಕಳು/ದೀವರ ಮಕ್ಕಳು", category: "2A", nigama: "Devraj Urs" },
  { name: "Aeliga - ಎಳಿಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Aelava - ಎಳವ", category: "2A", nigama: "Devraj Urs" },
  { name: "Gamalla - ಗಾಮಲ್ಲ", category: "2A", nigama: "Devraj Urs" },
  { name: "Goundla - ಗೌಂಡ್ಲ", category: "2A", nigama: "Devraj Urs" },
  { name: "Hale Paikaru - ಹಳೇ ಪೈಕರು", category: "2A", nigama: "Devraj Urs" },
  { name: "Hale Pike - ಹಳೇ ಪೈಕ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Illavan - ಇಲ್ಲಾವನ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Kalal - ಕಲಾಲ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Malayali Billava - ಮಲಯಾಳಿ ಬಿಲ್ಲವ", category: "2A", nigama: "Devraj Urs" },
  { name: "Naadar - ನಾಡರ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Naamadhari - ನಾಮಧಾರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Thiyaan/Thiyya - ಥಿಯಾನ್/ಥಿಯ್ಯ", category: "2A", nigama: "Devraj Urs" },
  { name: "Iliga - ಇಳಿಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Gondla - ಗೊಂಡ್ಲ", category: "2A", nigama: "Devraj Urs" },
  { name: "Tiyan/Thiyyaan - ತಿಯನ್/ಥಿಯ್ಯಾನ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Daevanga - ದೇವಾಂಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Daevang - ದೇವಾಂಗ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Koshti - ಕೋಷ್ಠಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Hatagaar - ಹಟಗಾರ್/ಹಟಗಾರ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Jade - ಜೇಡ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Winkaar - ವಿಂಕಾರ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Juloohi - ಜುಲೋಹಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Halkaar - ಹಲ್ಕಾರ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Hatagaar - ಹಟಗಾರ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Naeyke - ನೇಯ್ದೆ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kuruhina Shetty - ಕುರುಹಿನ ಶೆಟ್ಟಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kurni - ಕುರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Bili Magga - ಬಿಳಿಮಗ್ಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Togata/ Toogataru/ Togatiga - ತೊಗಟ/ತೊಗಟರು/ತೊಗಟಿಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Togataweera/Togatagera - ತೊಗಟವೀರ/ತೊಗಟಗೇರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Togatavira Kshatriya/Togaja Pushpanjali - ತೊಗಟವೀರ ಕ್ಷತ್ರಿಯ/ತೊಗಜ ಪುಷ್ಪಾಂಜಲಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Sooniga - ಸೋಣಿಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Jankhana - ಜಂಖಾನ", category: "2A", nigama: "Devraj Urs" },
  { name: "Airi - ಐರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Avir - ಅವಿರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Saale: Pattasaalae - ಸಾಲೆ:ಪಟ್ಟಸಾಲೆ", category: "2A", nigama: "Devraj Urs" },
  { name: "Padmasaalae/Padmashaali/Padmasaali - ಪದ್ಮಸಾಲೆ/ಪದ್ಮಶಾಲಿ/ ಪದ್ಮಸಾಲಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Saali/Pattasaali - ಸಾಲಿ/ಪಟ್ಟಸಾಲಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kaikoolan/Sengunder - ಕೈಕೋಳನ್/ಸೆಂಗುಂದರ್‌", category: "2A", nigama: "Devraj Urs" },
  { name: "Neykaar - ನೇಯ್ಕಾರ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Jaadar - ಜಾಡರ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Chandra - ಚಾಂದ್ರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Svakulasali/Svakulsali - ಸ್ವಕುಳಸಾಳಿ/ಸ್ವಕುಳಸಾಳೆ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kumbar - ಕುಂಬಾರ", category: "2A", nigama: "Kumbara Abhivrudhi" },
  { name: "Chakrasali - ಚಕ್ರಸಾಲಿ", category: "2A", nigama: "Kumbara Abhivrudhi" },
  { name: "Gunga - ಗುಣಗ", category: "2A", nigama: "Kumbara Abhivrudhi" },
  { name: "Ganagi - ಗಣಗಿ", category: "2A", nigama: "Kumbara Abhivrudhi" },
  { name: "Koyava - ಕೊಯವ", category: "2A", nigama: "Kumbara Abhivrudhi" },
  { name: "Kula - ಕುಲ", category: "2A", nigama: "Kumbara Abhivrudhi" },
  { name: "Kulaala - ಕುಲಾಲ", category: "2A", nigama: "Kumbara Abhivrudhi" },
  { name: "Kumbaar - ಕುಂಬಾರ್", category: "2A", nigama: "Kumbara Abhivrudhi" },
  { name: "kumbaarda - ಕುಂಬಾರ್ಡ", category: "2A", nigama: "Kumbara Abhivrudhi" },
  { name: "Kummaara - ಕುಮ್ಮಾರ", category: "2A", nigama: "Kumbara Abhivrudhi" },
  { name: "Kusavan - ಕುಸವನ್", category: "2A", nigama: "Kumbara Abhivrudhi" },
  { name: "Maulya - ಮೂಲ್ಯ", category: "2A", nigama: "Kumbara Abhivrudhi" },
  { name: "Sajjana Kumbaara - ಸಜ್ಜನ ಕುಂಬಾರ", category: "2A", nigama: "Kumbara Abhivrudhi" },
  { name: "Khumaara - ಖುಮಾರ", category: "2A", nigama: "Kumbara Abhivrudhi" },
  { name: "Kumbhara - ಕುಂಭಾರ", category: "2A", nigama: "Kumbara Abhivrudhi" },
  { name: "Khumbhaara - ಖುಂಭಾರ", category: "2A", nigama: "Kumbara Abhivrudhi" },
  { name: "Kulaalar - ಕುಲಾಲರ್", category: "2A", nigama: "Kumbara Abhivrudhi" },
  { name: "Tigala - ತಿಗಲ", category: "2A", nigama: "Devraj Urs" },
  { name: "Agnivamsha - ಅಗ್ನಿವಂಶ", category: "2A", nigama: "Devraj Urs" },
  { name: "Agnivanni - ಅಗ್ನಿವನ್ನಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Agnikulakshatriya - ಅಗ್ನಿಕುಲಕ್ಷತ್ರಿಯ", category: "2A", nigama: "Devraj Urs" },
  { name: "Dharmaraja Kaapu - ಧರ್ಮರಾಜ ಕಾಪು", category: "2A", nigama: "Devraj Urs" },
  { name: "Kaapu - ಕಾಪು", category: "3A", nigama: "Vokkaliga" },
  { name: "Palli - ಪಳ್ಳಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Shambhukulakshatriya - ಶಂಭುಕುಲ ಕ್ಷತ್ರಿಯ", category: "2A", nigama: "Devraj Urs" },
  { name: "Tigala - ತಿಗಳ", category: "2A", nigama: "Devraj Urs" },
  { name: "Vanniyar - ವನ್ನಿಯರ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Vannikulakshatriya - ವನ್ನಿಕುಲಕ್ಷತ್ರಿಯ", category: "2A", nigama: "Devraj Urs" },
  { name: "Tiglar - ತಿಗ್ಗರ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Kuroovan - ಕುರೋವನ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Hadapada - ಹಡಪದ", category: "2A", nigama: "Devraj Urs" },
  { name: "Huvaadiga - ಹೂವಾಡಿಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Hugaar - ಹುಗಾರ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Huugaar - ಹೂಗಾರ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Malgaar - ಮಾಲಗಾರ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Maali - ಮಾಲಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Moolmali - ಮೂಲ್‌ಮಾಲಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Phulmali - ಫುಲ್‌ಮಾಲಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Phulaari - ಫುಲಾರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Phalaari - ಫಲಾರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Jeer - ಜೀರಾ", category: "2A", nigama: "Devraj Urs" },
  { name: "Balija - ಬಲಿಜ", category: "3A", nigama: "Balija Samudaya Abhivrudhi Nigama" },
  { name: "Balajiga/Banajiga/Gowdabanajiga - ಬಲಜಿಗ/ಬಣಜಿಗ/ಗೌಡಬಣಜಿಗ", category: "3A", nigama: "Balija Samudaya Abhivrudhi Nigama" },
  { name: "Naydu - ನಾಯ್ಡು", category: "3A", nigama: "Balija Samudaya Abhivrudhi Nigama" },
  { name: "Telaga Balija/Telaga Banajiga - ತೆಲಗ ಬಲಿಜ/ತೆಲಗ ಬಣಜಿಗ", category: "3A", nigama: "Balija Samudaya Abhivrudhi Nigama" },
  { name: "Shetty Balija/Shetty Banajiga/Banajiga Shetty - ಶೆಟ್ಟಿ ಬಲಿಜ/ಶೆಟ್ಟಿ ಬಣಜಿಗ/ಬಣಜಿಗ ಶೆಟ್ಟಿ", category: "3A", nigama: "Balija Samudaya Abhivrudhi Nigama" },
  { name: "Dasara Balija/Dasare Baljiga - ದಾಸರ ಬಲಿಜ/ದಾಸರೆ ಬಲಜಿಗ", category: "3A", nigama: "Balija Samudaya Abhivrudhi Nigama" },
  { name: "Dasara Banajiga/Daasa Banajiga - ದಾಸರ ಬಣಜಿಗ/ದಾಸ ಬಣಜಿಗ", category: "3A", nigama: "Balija Samudaya Abhivrudhi Nigama" },
  { name: "Cusban - ಕಸ್ಟನ್", category: "3A", nigama: "Balija Samudaya Abhivrudhi Nigama" },
  { name: "Munnur/Munnar/Munnur Kaup - ಮುನ್ನೂರ/ಮುನ್ನಾರ್/ಮುನ್ನೂರ್ ಕಾಪು", category: "3A", nigama: "Balija Samudaya Abhivrudhi Nigama" },
  { name: "Balegara/Bale Banajiga/Bale Baljiga - ಬಳೆಗಾರ/ಬಳೆ ಬಣಜಿಗ/ಬಳೆ ಬಲಜಿಗ", category: "3A", nigama: "Balija Samudaya Abhivrudhi Nigama" },
  { name: "Bale Chetti/Banegara - ಬಳೆ ಚೆಟ್ಟಿ/ ಬಣಗಾರ", category: "3A", nigama: "Balija Samudaya Abhivrudhi Nigama" },
  { name: "Reddy (Balija) - ರೆಡ್ಡಿ (ಬಲಿಜ)", category: "3A", nigama: "Balija Samudaya Abhivrudhi Nigama" },
  { name: "Janappan - ಜನಪ್ಪನ್", category: "3A", nigama: "Balija Samudaya Abhivrudhi Nigama" },
  { name: "Uppara (Balija) - ಉಪ್ಪಾರ (ಬಲಿಜ)", category: "3A", nigama: "Balija Samudaya Abhivrudhi Nigama" },
  { name: "Tulaeru (Balija) - ತುಲೇರು (ಬಲಿಜ)", category: "3A", nigama: "Balija Samudaya Abhivrudhi Nigama" },
  { name: "Kodagaru - ಕೊಡಗರು", category: "3A", nigama: "Devraj Urs" },
  { name: "Maedara - ಮೇದರ", category: "1", nigama: "Devraj Urs" },
  { name: "Battar - ಬಟ್ಟರ", category: "1", nigama: "Devraj Urs" },
  { name: "Burned - ಬರ್ನೆಡ್", category: "1", nigama: "Devraj Urs" },
  { name: "Gauriga - ಗೌರಿಗ", category: "1", nigama: "Devraj Urs" },
  { name: "Gauv Rigga - ಗೌವ್ ರಿಗ", category: "1", nigama: "Devraj Urs" },
  { name: "Gauri - ಗೌರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Gauri Marata - ಗೌರಿ ಮರಾಠ", category: "1", nigama: "Devraj Urs" },
  { name: "Gauriga - ಗೌರಿಗ", category: "1", nigama: "Devraj Urs" },
  { name: "Maedari - ಮೇದರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Burud - ಬುರುಡ್", category: "1", nigama: "Devraj Urs" },
  { name: "Kadugolla - ಕಾಡುಗೊಲ್ಲ", category: "1", nigama: "Kadugoulla" },
  { name: "uppara - ಉಪ್ಪಾರ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Belder - ಬೆಲ್ಡರ್", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Chunaar - ಚುನಾರ್", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Gaawaadi - ಗಾವಾಡಿ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Kallu Kutiga Uppara - ಕಲ್ಲು ಕುಟಿಗ ಉಪ್ಪಾರ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Loonaari - ಲೋನಾರಿ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Maelu Sakkareyavaru - ಮೇಲು ಸಕ್ಕರೆಯವರು", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Maelu Sakkare - ಮೇಲು ಸಕ್ಕರೆ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Naamada Uppaara - ನಾಮದ ಉಪ್ಪಾರ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Padit / Padti - ಪಡಿತ್ / ಪಡ್ತಿ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Padithi - ಪಡಿತಿ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Paadi - ಪಾಡಿ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Sagara - ಸಗರ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Sunnagaara - ಸುಣ್ಣಗಾರ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Sunna Uppaara - ಸುಣ್ಣ ಉಪ್ಪಾರ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Uppaliga - ಉಪ್ಪಳಿಗ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Uppaligashetti - ಉಪ್ಪಳಿಗಶೆಟ್ಟಿ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Uppalian - ಉಪ್ಪಳಿಯನ್", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Uppeara - ಉಪ್ಪೇರ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Yakalaara - ಯಕಲಾರ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Ekkali - ಎಕ್ಕಲಿ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Goundi - ಗೌಂದಿ", category: "2A", nigama: "Uppara Avhivrudhi" },
  { name: "Besta - ಬೆಸ್ತ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Ambiga/Ambi - ಅಂಬಿಗ/ಅಂಬಿ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Baarika - ಬಾರಿ/ಬಾರಿಕ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Bester - ಬೆಸ್ತರ್", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Bhoi - ಭೋಯಿ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Rajaboi - ರಾಜಬೊಯಿ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Bunde-Beshtar - ಬುಂಡೆ - ಬೆಸ್ಥರ್", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Dalti - ದಾಲ್ಟಿ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "dawat - ದಾವತ್", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Gabbit - ಗಬಿಟ್", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Galadkonkani - ಗಲಾಡಕೊಂಕಣಿ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Ganga makkalu - ಗಂಗಮಕ್ಕಳು", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Gangakula - ಗಂಗಾಕುಲ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Gangamata - ಗಂಗಾಮತ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Gangamastha - ಗಂಗಾಮತಸ್ಥ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Gangaputra - ಗಂಗಾಪುತ್ರ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Gaurimata - ಗೌರಿಮತ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Bunde-Besta/Gunde Besta - ಬುಂಡೆ-ಬೆಸ್ತ/ಗುಂಡೆ ಬೆಸ್ತ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Harakantra - ಹರಕಂತ್ರ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Jalagaara - ಜಲಗಾರ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Kabbera / Kabbear - ಕಬ್ಬೇರ / ಕಬ್ಬರ್", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Kabbaliga - ಕಬ್ಬಲಿಗ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Kabbili - ಕಬ್ಬಿಲಿ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Kahar - ಕಹರ್", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Kharvi / Konkan Kharvi - ಖಾರ್ವಿ /ಕೊಂಕಣ ಖಾರ್ವಿ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Koli - ಕೋಳಿ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Koli Mahadev - ಕೋಳಿ ಮಹದೇವ್", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Mudder - ಮಡ್ಡರ್", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Meenagar - ಮೀನಗಾ‌ರ್", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Mogaveer - ಮೊಗವೀರ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Mogaer - ಮೊಗೇರ್", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Mukkawan - ಮುಕ್ಕವಾನ್", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Pariwara - ಪರಿವಾರ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Seveyar - ಸಿವಿಯರ್", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Sunagaara - ಸುಣಗಾರ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Tureya - ತೊರೆಯ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Pagi - ಪಾಗಿ", category: "1", nigama: "Ambhiga Abhivrudhi" },
  { name: "Jogi - ಜೋಗಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Joshi Sada Joshi - ಜೋಶಿ ಸದ ಜೋಶಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Kashikapaddi - ಕಾಶಿಕಪಾಡಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Katabu - ಕಟಬು", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Kel Kari - ಕೆಲ್‌ ಕಾರಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Killekyathas - ಕಿಳ್ಳೆಕ್ಯಾತಸ್", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Kolathi - ಕೋಲಾತಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Masani Yogi - ಮಸನಿಯ ಯೋಗಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Nandiwala-Joshi-Ghondal- Pul Malli - ನಂದಿವಾಲ-ಜೋಶಿ-ಘೋಂಡಳ್- ಪುಲ್ ಮಲ್ಲಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Nathapachithi, Dauri Gosavi - ನಾಥಪಚಿಥಿ, ಡೌರಿಗೋಸಾವಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Neer Shikari - ನೀರ್‌ ಶಿಕಾರಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Pangul - ಪಂಗುಲ್", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Pichaguntala - ಪಿಚಗುಂಟಲ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Sansiya - ಸನ್‌ಸಿಯ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Sarnia - ಸರನಿಯ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Sarodi - ಸರೊಡಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Shikkaligarh - ಶಿಕ್ಕಲಿಗಾರ್‌", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Tirumali - ತಿರುಮಲಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Padi - ಪಡಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Vagri - ವಗ್ರಿ", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "wydu - ವೈಡು", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Vasudev - ವಾಸುದೇವ್", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Vir - విరో", category: "1", nigama: "Alemari mathu Are Alemari Abhivrudhi" },
  { name: "Agasa - ಅಗಸ", category: "2A", nigama: "Madivala Machideva Abhvrudhi" },
  { name: "Chakala - ಚಕಲ", category: "2A", nigama: "Madivala Machideva Abhvrudhi" },
  { name: "Dhobi - ಧೋಬಿ", category: "2A", nigama: "Madivala Machideva Abhvrudhi" },
  { name: "Madiwala - ಮಡಿವಾಳ", category: "2A", nigama: "Madivala Machideva Abhvrudhi" },
  { name: "Mannan - ಮನ್ನನ್", category: "2A", nigama: "Madivala Machideva Abhvrudhi" },
  { name: "Parit - ಪರಿತ್", category: "2A", nigama: "Madivala Machideva Abhvrudhi" },
  { name: "Rajaka - ರಾಜಕ", category: "2A", nigama: "Madivala Machideva Abhvrudhi" },
  { name: "Sakala - ಸಕಲ", category: "2A", nigama: "Madivala Machideva Abhvrudhi" },
  { name: "Wannan - ವನ್ನನ್", category: "2A", nigama: "Madivala Machideva Abhvrudhi" },
  { name: "Welluteddan - ವೆಲ್ಲು ತೇಡನ್", category: "2A", nigama: "Madivala Machideva Abhvrudhi" },
  { name: "Sakalavaaddu - ಸಾಕಲವಾಡು", category: "2A", nigama: "Madivala Machideva Abhvrudhi" },
  { name: "Pariyala (South Kannada and Udupi District) - ಪರಿಯಾಳ (ದಕ್ಷಿಣ ಕನ್ನಡ ಮತ್ತು ಉಡುಪಿ ಜಿಲ್ಲೆ)", category: "2A", nigama: "Savita Samaaja Abhivrudhi" },
  { name: "Ambattan - ಅಂಬಟ್ಟನ್", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Bajantri - ಬಜಂತ್ರಿ", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Bhanddari - ಬಂಡಾರಿ", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Chauriya - ಚೌರಿಯ", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Kavutian - ಕವುಟಿಯನ್", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Kelasi - ಕೆಲಸಿ", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Kshaurika - ಕ್ಷೌರಿಕ", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Kshourad - ಕ್ಷೌರದ್", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Mahale - ಮಹಾಲೆ", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Mangala - ಮಂಗಳ", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Melagar - ಮೇಲಗಾರ", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Naddiga - ನಾಡಿಗ", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Napita - ನಾಪಿತ", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Navalig - ನವಲಿಗ್", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Navi - ನಾವಿ", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Nayanaja Kshatriya - ನಯನಜ ಕ್ಷತ್ರಿ", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Nhavi - ನಾವಿ", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Vajantri (North Kannada District) - ವಾಜಾಂತ್ರಿ (ಉತ್ತರ ಕನ್ನಡ ಜಿಲ್ಲೆ)", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Savita - ಸವಿತ", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Nayanaja Kshatriya - ನಯನಜ ಕ್ಷತ್ರಿ", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Naadiga - ನಾಡಿಗ", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Kshourik - ಕ್ಷೌರಿಕ್", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Kshourika - ಕ್ಷೌರಿಕ", category: "2A", nigama: "Savita Samaaja Abivrudhi" },
  { name: "Vishwakarma - ವಿಶ್ವಕರ್ಮ", category: "2A", nigama: "Vishwakarma" },
  { name: "Aachaari - ಆಚಾರಿ", category: "2A", nigama: "Vishwakarma" },
  { name: "Akkasaali - ಅಕ್ಕಸಾಲಿ", category: "2A", nigama: "Vishwakarma" },
  { name: "Ausaali - ಔಸಾಲಿ", category: "2A", nigama: "Vishwakarma" },
  { name: "Badiger - ಬಡಿಗರ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Badiwadda - ಬಡಿವಾಡ್ಡ", category: "2A", nigama: "Vishwakarma" },
  { name: "Bailu Akkasali - ಬೈಲು ಅಕ್ಕಸಾಲಿ", category: "2A", nigama: "Vishwakarma" },
  { name: "Bailu Kammaara - ಬೈಲು ಕಮ್ಮಾರ", category: "2A", nigama: "Vishwakarma" },
  { name: "Bogara - ಬೋಗಾರ", category: "2A", nigama: "Vishwakarma" },
  { name: "Chappegar - ಚಪ್ಪೇಗಾರ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Chaarodi - ಚಾರೋಡಿ", category: "2A", nigama: "Vishwakarma" },
  { name: "Konkani Aachaara - ಕೊಂಕಣಿ ಆಚಾರ", category: "2A", nigama: "Vishwakarma" },
  { name: "Dyvagnya Bhramana - ದೈವಜ್ಞಾಬ್ರಾಹ್ಮಣ", category: "2A", nigama: "Vishwakarma" },
  { name: "Gejjegara - ಗೆಜ್ಜೆಗಾರ", category: "2A", nigama: "Vishwakarma" },
  { name: "Kambar - ಕಂಬಾರ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Kammalan - ಕಮ್ಮಾಲನ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Kammaara - ಕಮ್ಮಾರ", category: "2A", nigama: "Vishwakarma" },
  { name: "Kansala - ಕಂಸಾಳ", category: "2A", nigama: "Vishwakarma" },
  { name: "Kansan - ಕಂಸನ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Kanchagarh - ಕಂಚಗಾರ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Kanchora - ಕಂಚೋರ", category: "2A", nigama: "Vishwakarma" },
  { name: "Bailpatar - ಬೈಲ್‌ಪತರ್‌", category: "2A", nigama: "Vishwakarma" },
  { name: "Kanchori - ಕಂಚೋರಿ", category: "2A", nigama: "Vishwakarma" },
  { name: "Kanchugaara - ಕಂಚುಗಾರ", category: "2A", nigama: "Vishwakarma" },
  { name: "Kansara - ಕಂಸಾರ", category: "2A", nigama: "Vishwakarma" },
  { name: "Lohar - ಲೋಹಾರ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Mesta - ಮೆಸ್ತ", category: "2A", nigama: "Vishwakarma" },
  { name: "Panchal - ಪಂಚಾಲ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Pathar - ಪತ್ತರ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Sohgar - ಸೋಹಗಾರ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Silchi - ಸಿಲ್ಚಿ", category: "2A", nigama: "Vishwakarma" },
  { name: "Kasar - ಕಸಾರ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Sonar - ಸೋನಾರ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Soni - ಸೋನಿ", category: "2A", nigama: "Vishwakarma" },
  { name: "Sutar - ಸುತಾರ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Tasehan - ತಸೆಹಾನ್", category: "2A", nigama: "Vishwakarma" },
  { name: "VishwaBrahman - ವಿಶ್ವಬ್ರಾಹ್ಮಣ", category: "2A", nigama: "Vishwakarma" },
  { name: "Thattan - ಥಟ್ಟನ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Aksali - ಅಕ್ಸಾಲಿ", category: "2A", nigama: "Vishwakarma" },
  { name: "Kamsali - ಕಂಸಾಲ್", category: "2A", nigama: "Vishwakarma" },
  { name: "Badagi - ಬಡಗಿ", category: "2A", nigama: "Vishwakarma" },
  { name: "Vokkaliga - ಒಕ್ಕಲಿಗ", category: "3A", nigama: "Vokkaliga" },
  { name: "Vokkaliga - ವಕ್ಕಲಿಗ", category: "3A", nigama: "Vokkaliga" },
  { name: "Sarpa Vokkaliga - ಸರ್ಪ ಒಕ್ಕಲಿಗ", category: "3A", nigama: "Vokkaliga" },
  { name: "Hallikar Vokkaliga - ಹಳ್ಳಿಕಾರ್ ಒಕ್ಕಲಿಗ", category: "3A", nigama: "Vokkaliga" },
  { name: "Namdhari Vokkaliga - ನಾಮಧಾರಿ ಒಕ್ಕಲಿಗ", category: "3A", nigama: "Vokkaliga" },
  { name: "Gangadkar Vokkaliga - ಗಂಗಡ್ಕಾರ್ ಒಕ್ಕಲಿಗ", category: "3A", nigama: "Vokkaliga" },
  { name: "Das Vokkaliga - ದಾಸ್ ಒಕ್ಕಲಿಗ", category: "3A", nigama: "Vokkaliga" },
  { name: "Reddy Vokkaliga - ರೆಡ್ಡಿ ಒಕ್ಕಲಿಗ", category: "3A", nigama: "Vokkaliga" },
  { name: "Marasu Vokkaliga - ಮರಸು ಒಕ್ಕಲಿಗ", category: "3A", nigama: "Vokkaliga" },
  { name: "Gowda - ಗೌಡ", category: "3A", nigama: "Vokkaliga" },
  { name: "Hallikar - ಹಳ್ಳಿಕಾರ್", category: "3A", nigama: "Vokkaliga" },
  { name: "Kunchitiga - ಕುಂಚಿಟಿಗ", category: "3A", nigama: "Vokkaliga" },
  { name: "Kaup - ಕಾಪು", category: "3A", nigama: "Vokkaliga" },
  { name: "Heggade - ಹೆಗ್ಗಡೆ", category: "3A", nigama: "Vokkaliga" },
  { name: "Kamma - ಕಮ್ಮ", category: "3A", nigama: "Vokkaliga" },
  { name: "Raddy - ರಡ್ಡಿ", category: "3A", nigama: "Vokkaliga" },
  { name: "Gounder - ಗೌಂಡರ್", category: "3A", nigama: "Vokkaliga" },
  { name: "Namadhari Gowda - ನಾಮಧಾರಿ ಗೌಡ", category: "3A", nigama: "Vokkaliga" },
  { name: "Uppina Kolaga/ Uttama Kolaga - ಉಪ್ಪಿನ ಕೊಳಗ/ಉತ್ತಮ ಕೊಳಗ", category: "3A", nigama: "Vokkaliga" },
  { name: "Veerashaiva Lingayat - ವೀರಶೈವ ಲಿಂಗಾಯತ", category: "3B", nigama: "Veerashaiva Lingayat" },
  { name: "Panchamasali Lingayat - ಪಂಚಮಸಾಲಿ ಲಿಂಗಾಯತ", category: "3B", nigama: "Veerashaiva Lingayat" },
  { name: "Maratha/Marata - ಮರಾತ/ಮರಾಠ", category: "3B", nigama: "Maratha" },
  { name: "Are-Kshatriya/Are-Maratha/Aramarata - ಅರೆ ಕ್ಷತ್ರಿ/ಅರೆ ಮರಾಠ/ಅರಮರಾಠ", category: "3B", nigama: "Maratha" },
  { name: "Arya/Aryaru - ಆರ್ಯ/ಆರ್ಯರು", category: "3B", nigama: "Maratha" },
  { name: "Konkana Maratha - ಕೊಂಕಣ ಮರಾಠ", category: "3B", nigama: "Maratha" },
  { name: "Kshatriya Maratha - ಕ್ಷತ್ರಿಯ ಮರಾಠ", category: "3B", nigama: "Maratha" },
  { name: "Kulwadi - ಕುಳವಾಡಿ", category: "3B", nigama: "Maratha" },
  { name: "Agamudi - ಅಗಮುಡಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Ambalakaran - ಅಂಬಲಕಾರನ್", category: "1", nigama: "Devraj Urs" },
  { name: "Dasari - ದಾಸರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Ambalakarma - ಅಗಮುಡಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Dasaru - ಅಂಬಲಕಾರನ್", category: "1", nigama: "Devraj Urs" },
  { name: "Muttarasi - ದಾಸರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Chakravadya Das - ಅಗಮುಡಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Muttaracha - ಅಂಬಲಕಾರನ್", category: "1", nigama: "Devraj Urs" },
  { name: "Dang-Dasar - ದಾಸರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Baggaru - ಅಂಬಲಕಾರನ್", category: "1", nigama: "Devraj Urs" },
  { name: "Devadasi - ದಾಸರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Bavandi - ಬವಂದಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Basavi - ಬಸವಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Bavaji - ಬಾವಾಜಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Bhavin - ಭಾವಿನ್", category: "1", nigama: "Devraj Urs" },
  { name: "Atith - ಅತಿತ್", category: "1", nigama: "Devraj Urs" },
  { name: "Bogam - ಬೋಗಮ್", category: "1", nigama: "Devraj Urs" },
  { name: "Bhavani - ಬವಾನಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Ganika - ಗಣಿಕ", category: "1", nigama: "Devraj Urs" },
  { name: "Davari - ಡವರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Kalavant - ಕಲಾವಂತ್", category: "1", nigama: "Devraj Urs" },
  { name: "Gosai - ಗೋಸಾಯಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Nat - ನಟ್", category: "1", nigama: "Devraj Urs" },
  { name: "Gusai - ಗುಸಾಯ್", category: "1", nigama: "Devraj Urs" },
  { name: "Natuva - ನಟುವ", category: "1", nigama: "Devraj Urs" },
  { name: "Helova - ಹೆಳೊವ", category: "1", nigama: "Devraj Urs" },
  { name: "Patramela - ಪತ್ರಮೇಳ", category: "1", nigama: "Devraj Urs" },
  { name: "Holeva - ಹೊಲೆವ", category: "1", nigama: "Devraj Urs" },
  { name: "Ghisaade - ಘಿಸಾಡೆ", category: "1", nigama: "Devraj Urs" },
  { name: "Pichagunta - ಪಿಚಗುಂಟ", category: "1", nigama: "Devraj Urs" },
  { name: "Pichiguntala - ಪಿಚಿಗುಂಟಲ", category: "1", nigama: "Devraj Urs" },
  { name: "Goniga Mane - ಗೋಣಿಗ ಮನೆ", category: "1", nigama: "Devraj Urs" },
  { name: "24 Mane Telugu Shetti - 24 ಮನೆ ತೆಲುಗು ಶೆಟ್ಟಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Byargi - ಬ್ಯಾರಗಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Gonichitti - ಗೋಣಿಚಿಟ್ಟಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Sadushetti - ಸಾದುಸೆಟ್ಟಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Salaparu - ಸಲಪರು", category: "1", nigama: "Devraj Urs" },
  { name: "Gurav - ಗುರವ್", category: "1", nigama: "Devraj Urs" },
  { name: "Takari - ಟಕರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Tambala - ತಾಂಬ", category: "1", nigama: "Devraj Urs" },
  { name: "Tambli - ತಾಂಬಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Uccilian - ಉಚ್ಚಿಲಿಯನ್", category: "1", nigama: "Devraj Urs" },
  { name: "Gurkha - ಗುರ್ಖಾ", category: "1", nigama: "Devraj Urs" },
  { name: "Halavakki Okkalu - ಹಾಲವಕ್ಕಿ ಒಕ್ಕಲ್", category: "1", nigama: "Devraj Urs" },
  { name: "Bogad - ಬೋಗಡ್", category: "1", nigama: "Devraj Urs" },
  { name: "Halavakki Vakkal - ಹಾಲವಕ್ಕಿ ವಕ್ಕಲ್", category: "1", nigama: "Devraj Urs" },
  { name: "Begadi - ಬೇಗಾಡಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Atte Okkalu - ಅಟ್ಟೆ ಒಕ್ಕಲು", category: "1", nigama: "Devraj Urs" },
  { name: "Bagali - ಬಗಲಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Gam Gavda - ಗಾಮ್ ಗವಡ", category: "1", nigama: "Devraj Urs" },
  { name: "Bogadi - ಬೋಗಾಡಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Gam Okkalu - ಗಾಮ್ ಒಕ್ಕಲು", category: "1", nigama: "Devraj Urs" },
  { name: "Budoodki - ಬುಡೂಡ್ಮಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Grama Okkalu - ಗ್ರಾಮ ಒಕ್ಕಲು", category: "1", nigama: "Devraj Urs" },
  { name: "Chetri - ಚೇಟ್ಲಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Halakki Okkalu - ಹಾಲಕ್ಕಿ ಒಕ್ಕಲು", category: "1", nigama: "Devraj Urs" },
  { name: "Devari - ದೇವರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Kare Okkalu - ಕರೆ ಒಕ್ಕಲು", category: "1", nigama: "Devraj Urs" },
  { name: "Kuncha Vakkalu - ಕುಂಚ ವಕ್ಕಲು", category: "1", nigama: "Devraj Urs" },
  { name: "Shilpakal - ಶಿಲ್ಪಕಲ್", category: "1", nigama: "Devraj Urs" },
  { name: "Vakkal - ವಕ್ಕಲ್", category: "1", nigama: "Devraj Urs" },
  { name: "Modig - ಮೋದಿಗ", category: "1", nigama: "Devraj Urs" },
  { name: "Gavda - ಗವಡ", category: "1", nigama: "Devraj Urs" },
  { name: "Panna - ಪನ್ನ", category: "1", nigama: "Devraj Urs" },
  { name: "Panasa - ಪನಸ", category: "1", nigama: "Devraj Urs" },
  { name: "Grama Vakkalu - ಗ್ರಾಮ ವಕ್ಕಲು", category: "1", nigama: "Devraj Urs" },
  { name: "Pingale - ಪಿಂಗಳೆ", category: "1", nigama: "Devraj Urs" },
  { name: "Budbudkala - ಬುಡ್ಬುಡಕಾಲ", category: "1", nigama: "Devraj Urs" },
  { name: "Jangala - ಜಂಗಾಲ", category: "1", nigama: "Devraj Urs" },
  { name: "Telugu Jangama - ತೆಲುಗು ಜಂಗಮ", category: "1", nigama: "Devraj Urs" },
  { name: "Pakanathi Jangama - ಪಾಕನಾತಿ ಜಂಗಮ", category: "1", nigama: "Devraj Urs" },
  { name: "Ladaru/Ladara/Lada - ಲಾಡರು/ಲಾಡರ/ಲಾಡ", category: "1", nigama: "Devraj Urs" },
  { name: "Lad/Krityalad/Sugandhilad - ಲಾಡ್/ಕೃತಿಯಲಾಡ್/ಸುಗಂಧಿಲಾಡ್", category: "1", nigama: "Devraj Urs" },
  { name: "Brahma Kapali - ಬ್ರಹ್ಮ ಕಪಾಲಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Elagal - ಎಲೆಗಾಲ್", category: "1", nigama: "Devraj Urs" },
  { name: "Jogar - ಜೋಗಾ", category: "1", nigama: "Devraj Urs" },
  { name: "Malaya - ಮಲಯ", category: "1", nigama: "Devraj Urs" },
  { name: "Mudar - ಮೇದರ", category: "1", nigama: "Devraj Urs" },
  { name: "Kapali - ಕಪಾಲಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Raval - ರಾವಳ್", category: "1", nigama: "Devraj Urs" },
  { name: "Sanjogi - ಸಂಜೋಗಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Sannyasi - ಸನ್ಯಾಸಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Khanjir Bhatt - ಖಂಜಿರ್ ಭಾಟ್", category: "1", nigama: "Devraj Urs" },
  { name: "Gouriga - ಗೌರಿಗ", category: "1", nigama: "Devraj Urs" },
  { name: "Kanjar - ಕಂಜ", category: "1", nigama: "Devraj Urs" },
  { name: "Khanjar Bhatt - ಖಂಜ ಭಾಟ್", category: "1", nigama: "Devraj Urs" },
  { name: "Kashikapi - ಕಾಶಿಕಪಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Mudar - ಮುದ", category: "1", nigama: "Devraj Urs" },
  { name: "Katabar - ಕಟಬ", category: "1", nigama: "Devraj Urs" },
  { name: "Nayiri/Nyari - ನಾಯಿರಿ/ನ್ಯಾರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Katek - ಕಾಟೆಕ್", category: "1", nigama: "Devraj Urs" },
  { name: "Othiri - ಓತಿರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Arey - ಅರೇಯ್", category: "1", nigama: "Devraj Urs" },
  { name: "Are Kasai - ಅರೆ ಕಸಾಯ್", category: "1", nigama: "Devraj Urs" },
  { name: "Pangyusal - ಪಾಂಗ್ಯುಸಲ್", category: "1", nigama: "Devraj Urs" },
  { name: "Arikatikelu - ಅರಿಕಾಟಿಕೇಲು", category: "1", nigama: "Devraj Urs" },
  { name: "Panika - ಪಣಿಕ", category: "1", nigama: "Devraj Urs" },
  { name: "Kalal Katek - ಕಲಾಲ್ ಖಾಟೆಕ್", category: "1", nigama: "Devraj Urs" },
  { name: "Ray Rawat - ರಾಯ ರಾವತ್", category: "1", nigama: "Devraj Urs" },
  { name: "Kasab - ಕಸಾಬ್", category: "1", nigama: "Devraj Urs" },
  { name: "Rawat - ರಾವತ್", category: "1", nigama: "Devraj Urs" },
  { name: "Kasai - ಕಸಾಯ್", category: "1", nigama: "Devraj Urs" },
  { name: "Rainudas - ರೈನುದಾಸ್", category: "1", nigama: "Devraj Urs" },
  { name: "Maratti - ಮರಟ್ಟಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Satarkar - ಸತಾರ್ಕ", category: "1", nigama: "Devraj Urs" },
  { name: "Suryavansh Kshatriya - ಸೂರ್ಯವಂಶ ಕ್ಷತ್ರಿಯ", category: "1", nigama: "Devraj Urs" },
  { name: "Kodugu Kapal - ಕೊಡುಗು ಕಾಪಾಳ", category: "1", nigama: "Devraj Urs" },
  { name: "Sikkaligar - ಸಿಕ್ಕಲಿಗಾರ", category: "1", nigama: "Devraj Urs" },
  { name: "Kolari - ಕೊಲಾರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Shikalagar - ಶಿಕಾಲಗಾ", category: "1", nigama: "Devraj Urs" },
  { name: "Kalayiri - ಕಲಾಯಿರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Somavansh Arya Kshatriya - ಸೋಮವಂಶ ಆರ್ಯ ಕ್ಷತ್ರಿಯ", category: "1", nigama: "Devraj Urs" },
  { name: "Koleri - ಕೊಲೇರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Chitara - ಚಿತಾರ", category: "1", nigama: "Devraj Urs" },
  { name: "Chitragar - ಚಿತ್ರಗಾರ", category: "1", nigama: "Devraj Urs" },
  { name: "Kotari - ಕೊಟಾರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Jeeragar - ಜೀರಗಾರ", category: "1", nigama: "Devraj Urs" },
  { name: "Kottari - ಕೊಟ್ಟಾರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Najaband - ನಾಜಬಂದ್", category: "1", nigama: "Devraj Urs" },
  { name: "Kothari - ಕೊಠಾರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Nalaband - ನಾಲಬಂದ್", category: "1", nigama: "Devraj Urs" },
  { name: "Kudubi - ಕುಡುಬಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Tambat - ತಾಂಬಟ್", category: "1", nigama: "Devraj Urs" },
  { name: "Kumbri Marathi - ಕುಂಬ್ರಿ ಮರಾಠಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Takankar - ತಕನ್ಕರ", category: "1", nigama: "Devraj Urs" },
  { name: "Kunabi - ಕುಣಬಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Teva - ತೇವ", category: "1", nigama: "Devraj Urs" },
  { name: "Kulawadi - ಕುಳವಾಡಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Kalari - ಕಲರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Kanabi - ಕಣಬಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Kolla - ಕಲ್ಲ", category: "1", nigama: "Devraj Urs" },
  { name: "Kurma - ಕುರ್ಮ", category: "1", nigama: "Devraj Urs" },
  { name: "Marava - ಮರವ", category: "1", nigama: "Devraj Urs" },
  { name: "Kurmi - ಕುರ್ಮಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Tilarai - ತಿಲಾರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Tirali - ತಿರಳಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Gavli - ಗಾವ್ಳಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Gavali - ಗಾವಳಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Eralu - ಏರಾಲು", category: "1", nigama: "Devraj Urs" },
  { name: "Erkal - ಎರ್ಕಲ", category: "1", nigama: "Devraj Urs" },
  { name: "Anubaru - ಅನುಬರು", category: "1", nigama: "Devraj Urs" },
  { name: "Irakal - ಇರಕಲ", category: "1", nigama: "Devraj Urs" },
  { name: "Atanabaru - ಅಟನಬರು", category: "1", nigama: "Devraj Urs" },
  { name: "KaiKadi - ಕೈ ಕಡಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Hanabar - ಹಣಬ", category: "1", nigama: "Devraj Urs" },
  { name: "Koragar - ಕೊರಗಾ", category: "1", nigama: "Devraj Urs" },
  { name: "Kavaadi - ಕಾವಡಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Kormashetti - ಕೊರ್ಮಶೆಟ್ಟಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Kolayan - ಕೊಲಯನ್", category: "1", nigama: "Devraj Urs" },
  { name: "Erukula - ಎರುಕುಲ", category: "1", nigama: "Devraj Urs" },
  { name: "Krishna Gawli - ಕೃಷ್ಣ ಗೌಳಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Bailpatar - ಬೈಲ್ಪತ", category: "1", nigama: "Devraj Urs" },
  { name: "Bilpatar - ಬಿಲಪತ", category: "1", nigama: "Devraj Urs" },
  { name: "Bajeniya - ಬಜೆನಿಯ", category: "1", nigama: "Devraj Urs" },
  { name: "Krishna Golla - ಕೃಷ್ಣ ಗೊಲ್ಲ", category: "1", nigama: "Devraj Urs" },
  { name: "Maniyani - ಮಣಿಯಾನಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Urali - ಉರಳಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Deriya - ಡೇರಿಯ", category: "1", nigama: "Devraj Urs" },
  { name: "Telugu Gowda - ತೆಲುಗು ಗೌಡ", category: "1", nigama: "Devraj Urs" },
  { name: "Bhargi - ಭಾರ್ಗಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Banjari - ಬಂಜರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Brinjari - ಬಿಂಜಾರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Vanjara - ವಂಜಾರ", category: "1", nigama: "Devraj Urs" },
  { name: "Vanjari - ವಂಜಾರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Lambaid - ಲಂಬ್ರೆಡ್", category: "1", nigama: "Devraj Urs" },
  { name: "Modikara - ಮೋದಿಕಾರ", category: "1", nigama: "Devraj Urs" },
  { name: "Gore or Goriya - ಗೋರೆ ಅಥವಾ ಗೋರಿಯ", category: "1", nigama: "Devraj Urs" },
  { name: "Modikar - ಮೋದಿಕ", category: "1", nigama: "Devraj Urs" },
  { name: "Bendar - ಬೆಂಡ", category: "1", nigama: "Devraj Urs" },
  { name: "Gondali - ಘೋಂದಲಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Berad - ಬೆರಾಡ್", category: "1", nigama: "Devraj Urs" },
  { name: "Gondaliga - ಗೊಂದಲಿಗ", category: "1", nigama: "Devraj Urs" },
  { name: "Boya - ಬೋಯ", category: "1", nigama: "Devraj Urs" },
  { name: "Nayaka Makkalu - ನಾಯಕಮಕ್ಕಳು", category: "1", nigama: "Devraj Urs" },
  { name: "Javeri - ಜವೇರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Nayakvadi - ನಾಯಕ್ವಾಡಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Javari - ಜವರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Paalegaara - ಪಾಳೇಗಾರ", category: "1", nigama: "Devraj Urs" },
  { name: "Johari - ಜೋಹರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Remoshi - ರೆಮೋಶಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Kamatti - ಕಾಮಟ್ಟಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Valmiki Makkalu - ವಾಲ್ಮೀಕಿ ಮಕ್ಕಳು", category: "1", nigama: "Devraj Urs" },
  { name: "Kaman - ಕಮನ್", category: "1", nigama: "Devraj Urs" },
  { name: "Vedan - ವೇದನ್", category: "1", nigama: "Devraj Urs" },
  { name: "Kanjari - ಕಂಜರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Myasa Nayak - ಮ್ಯಾಸ ನಾಯಕ", category: "1", nigama: "Devraj Urs" },
  { name: "Kanjir - ಕಂಜಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Aras Nayak - ಅರಸ್ ನಾಯಕ", category: "1", nigama: "Devraj Urs" },
  { name: "Khelkari - ಖೇಲ್ಕರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Byada - ಬ್ಯಾಡ", category: "1", nigama: "Devraj Urs" },
  { name: "kolahtagi - ಕೋಲ್ಡ್ ಟಿಗಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Haran Shikari - ಹರನ್ ಶಿಕಾರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Saranta - ಸಾರಂತ", category: "1", nigama: "Devraj Urs" },
  { name: "Chigari Betagar - ಚಿಗರಿ ಬೇಟಗಾ", category: "1", nigama: "Devraj Urs" },
  { name: "Sarori - ಸರೋರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Wafri - ವಾಫ್ರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Bedaru - ಬೇಡರು", category: "1", nigama: "Devraj Urs" },
  { name: "Vagari - ವಾಗರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Yadav - ಯಾದವ್", category: "1", nigama: "Devraj Urs" },
  { name: "Bargi - ಬಾರ್ಗಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Asthanagoll - ಆಸ್ಥಾನಗೊಲ್ಲ", category: "1", nigama: "Devraj Urs" },
  { name: "Bovari - ಬೋವರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Yadav - ಯಾದವ", category: "1", nigama: "Devraj Urs" },
  { name: "Fasachari - ಫಸಾಚಾರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Adavigoll - ಅಡವಿಗೊಲ್ಲ", category: "1", nigama: "Devraj Urs" },
  { name: "Hirshikari - ಹಿರ್ಶಿಕಾರಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Gopali - ಗೋಪಾಲಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Garudiga - ಗಾರುಡಿಗ", category: "1", nigama: "Devraj Urs" },
  { name: "Gawli - ಗೌಳಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Garadiga - ಗಾರಡಿಗ", category: "1", nigama: "Devraj Urs" },
  { name: "Paradhis - ಪರಧೀಸ್", category: "1", nigama: "Devraj Urs" },
  { name: "Girani Waddar - ಗಿರಣಿ ವಡ್ಡ", category: "1", nigama: "Devraj Urs" },
  { name: "Tudug Woddar - ತುಡುಗ್ ವೊಡ್ಡ", category: "1", nigama: "Devraj Urs" },
  { name: "Kallu Waddar - ಕಲ್ಲು ವಡ್ಡರ್", category: "1", nigama: "Devraj Urs" },
  { name: "Mannu Woddar - ಮಣ್ಣು ವೊಡ್ಡ", category: "1", nigama: "Devraj Urs" },
  { name: "Bhandi Woddar - ಭಾಂದಿ ವೊಡ್ಡ", category: "1", nigama: "Devraj Urs" },
  { name: "Bhoyi - ಭೋಯಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Harikanthra - ಹರಿಕಂತ್ರ", category: "1", nigama: "Devraj Urs" },
  { name: "Khariya - ಖಾರಿಯ", category: "1", nigama: "Devraj Urs" },
  { name: "boyi - ಬೋವಿ", category: "1", nigama: "Devraj Urs" },
  { name: "Ban (Kodagu District) - ಬಣ್ಣ (ಕೊಡಗು ಜಿಲ್ಲೆ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Devadiga - ದೇವಾಡಿಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Eliga - ಎಳಿಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Devali - ದೇವಲಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Elava - ಎಳವ", category: "2A", nigama: "Devraj Urs" },
  { name: "Moyili - ಮೊಯಿಲಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Padiyar - ಪಡಿಯಾ", category: "2A", nigama: "Devraj Urs" },
  { name: "Gaundla - ಗೌಂಡ", category: "2A", nigama: "Devraj Urs" },
  { name: "Seregara - ಸೇರೆಗಾರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Surveygara - ಸರ್ವೇಗಾರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Hale Paik - ಹಳೇ ಪೈಕ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Sheregara - ಶೇರಗಾರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Sapaliga - ಸಪಲಿಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Bandari - ಬಂಧಾರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Nadar - ನಾಡ", category: "2A", nigama: "Devraj Urs" },
  { name: "Belbad - ಬೆದ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Namadhari - ನಾಮಧಾರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Thiyan/Thiyya - ಥಿಯಾನ್/ಥಿಯ್ಯ", category: "2A", nigama: "Devraj Urs" },
  { name: "Divar - ದೀವರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Thiyan/Thiyan - ತಿಯನ್/ಥಿಯಾನ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Kodagu Heggade (Kodagu District) - ಕೊಡಗು ಹೆಗ್ಗಡೆ (ಕೊಡಗು ಜಿಲ್ಲೆ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Deva Children/Devar - ದೇವರ ಮಕ್ಕಳು/ದೀವರ ಮಕ್ಕಳು", category: "2A", nigama: "Devraj Urs" },
  { name: "Bahuroopi - ಬಹುರೂಪಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Bakadra - ಬಕದ್ರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Batala - ಬತಾಲ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Battal - ಬಟ್ಟಲ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Bhat - ಭಾಟ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Binapatta - ಬಿನ್ನಪಟ್ಟ", category: "2A", nigama: "Devraj Urs" },
  { name: "Bingi - బింగి", category: "2A", nigama: "Devraj Urs" },
  { name: "Bagadi - ಬಗಡಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Bagadi - ಬಗಾಡಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Bagdi - ಬಗ್ಗಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Chalian - ಚಲಿಯನ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Theruvan - ತೆರುವನ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Kuruba - ಕುರುಬ", category: "2A", nigama: "Devraj Urs" },
  { name: "Challiya - ಚಲ್ಲಿ ಯ", category: "2A", nigama: "Devraj Urs" },
  { name: "Chamboti - ಚಂಬೋಟಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Chambukatti - ಚಂಬುಕುಟ್ಟಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kurab - ಕುರಬ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Ghadi - ಘಾಡಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kuruban - ಕುರುಬನ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Gadiga - ಗಾಡಿಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kurumba - ಕುರುಂಬ", category: "2A", nigama: "Devraj Urs" },
  { name: "Gunagi - ಗುನಗಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kuruba - ಕುರುಬ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Ghadsi - ಘಾಡ್ಲಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Gosavi - ಗೋಸಾವಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Gosayan - ಗೋಸಾಯನ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Gujar - ಗುಜಾ", category: "2A", nigama: "Devraj Urs" },
  { name: "Gujar - ಗುಜಾರ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Gurava - ಗುರವ", category: "2A", nigama: "Devraj Urs" },
  { name: "Gurov - ಗುರೋವ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Gabbitt - ಗಬ್ಬಿಟ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Gapit - ಗಪಿಟ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Gabit - ಗಾಬಿಟ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Daalij - ದಾಲಿಜ", category: "2A", nigama: "Devraj Urs" },
  { name: "Handewajeer - ಹಂಡೇವಜೀರ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Aghori - ಅಘೋರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Handeshwath - ಹಂಡೇಶ್ವತ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Kakar Munda - ಕಕರ್ ಮುಂಡಾ", category: "2A", nigama: "Devraj Urs" },
  { name: "Ajnani - ಅಜ್ಞಾನಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Ambalavasi - ಅಂಬಲವಾಸಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Huga - ಹುಗಾ", category: "2A", nigama: "Devraj Urs" },
  { name: "Anduran - ಅಂಡೂರನ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Ateri - ಅಟೇರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Athari - ಅಥರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Pandara - ಪಂಡಾರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Panab - ಪನಬ", category: "2A", nigama: "Devraj Urs" },
  { name: "Pannekar Konkani - ಪನ್ನೇಕರ ಕೊಂಕಣಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kaadu Konkani - ಕಾಡು ಕೊಂಕಣಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Karikudumbi - ಕರಿಕುಡು೦ಬಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Rajapuri - ರಾಜಪುರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Karuva - ಕರುವ", category: "2A", nigama: "Devraj Urs" },
  { name: "Khathek - ಖಾಟೆಕ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Baalwalikar - ಬಾಲವಾಲಿಕರ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Katuk - ಕಟುಕ", category: "2A", nigama: "Devraj Urs" },
  { name: "Saniyar - ಸನಿಯಾ", category: "2A", nigama: "Devraj Urs" },
  { name: "Katuga - ಕಟುಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Shanan - ಶಾನನ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Bogar - ಬೋಗಾ", category: "2A", nigama: "Devraj Urs" },
  { name: "Sudir - ಸುದಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kustin - ಕಸ್ಟಿನ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Sudra - ಸೂದ್ರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kolayiri - ಕೊಲಾಯಿರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kulawadi Marathi - ಕುಳವಾಡಿ ಮರಾಟಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kolyiri - ಕೊಲ್ಯಿರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Sutsaali - ಸುಟ್ಬಾಲಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kanisan - ಕಣಿಸನ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Tachayiri - ತಚಾಯಿರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Balayya (Dakshina Kannada and Udupi District) - ಬಲ್ಯಾಯ (ದಕ್ಷಿಣ ಕನ್ನಡ ಮತ್ತು ಉಡುಪಿ ಜಿಲ್ಲೆ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Kaniyar - ಕಣಿಯ", category: "2A", nigama: "Devraj Urs" },
  { name: "Gavandi - ಗವಂಡಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kaniyaru - ಕಣಿಯರು", category: "2A", nigama: "Devraj Urs" },
  { name: "Govandi - ಗೋವಂಡಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kaniya - ಕಣಿಯ", category: "2A", nigama: "Devraj Urs" },
  { name: "Vettuvan - ವೆಟ್ಟುವನ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Kaniyan (Mysore District excluding Kolleagar Taluk) - ಕಣಿಯನ್ (ಮೈಸೂರು ಜಿಲ್ಲೆಯ ಕೊಳ್ಳೆಗಾರ ತಾಲ್ಲೂಕು ಹೊರತುಪಡಿಸಿ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Excler - ಎಕ್ಸ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kanyan - ಕನ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Yaklar - ಯಕ್ಷ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kutuma - ಕುಟುಮ", category: "2A", nigama: "Devraj Urs" },
  { name: "Marta - ಮರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Egaalika - ಈಗಳಿಕ", category: "2A", nigama: "Devraj Urs" },
  { name: "Gatti/Gattiyavaru - ಗಟ್ಟಿ/ಗಟ್ಟಿಯವರು", category: "2A", nigama: "Devraj Urs" },
  { name: "Marayan - ಮರಯನ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Poledava/Poladavaru - ಪೊಲೆದವ/ಪೋಲದವರು", category: "2A", nigama: "Devraj Urs" },
  { name: "Maravan - ಮರವನ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Gudigara - ಗುಡಿಗಾರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Murrari - ಮುದ್ರಾರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Darji - ದರ್ಜಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Nadore - ನಾಡೋರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Uppunadar/Up Nadore - ಉಪ್ಪು ನಾಡರ್/ಉಪ ನಾಡೊರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Chippi - ಚಿಪ್ಪಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Torke Nador - ತೊರ್ಕೆ ನಾಡೋರ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Chippiga - ಚಿಪ್ಪಿಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Nadore - ನಾಡೋ", category: "2A", nigama: "Devraj Urs" },
  { name: "Simpi - ಶಿಂಪಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Nadavar - ನಾಡವ", category: "2A", nigama: "Devraj Urs" },
  { name: "Shimpi - ಶಿಂಪಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Nadava - ನಾಡವ", category: "2A", nigama: "Devraj Urs" },
  { name: "Saayi - ಸಾಯಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Uppunador: Sub - ಉಪ್ಪು ನಾಡೋರ : ಉಪ", category: "2A", nigama: "Devraj Urs" },
  { name: "Miral - ಮಿರಾಲ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Rangari - ರಂಗಾರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Rangrej - ರಂಗೇಜ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Nilari - ನಿಲಾರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Namadev - ನಾಮದೇವ", category: "2A", nigama: "Devraj Urs" },
  { name: "Namadev Simpi - ನಾಮದೇವ ಸಿಂಪಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Rangare - ರಂಗಾರೆ", category: "2A", nigama: "Devraj Urs" },
  { name: "Neelagar - ನೀಲಗಾ", category: "2A", nigama: "Devraj Urs" },
  { name: "Amma Kodava - ಅಮ್ಮ ಕೊಡವ", category: "2A", nigama: "Devraj Urs" },
  { name: "Devanga - ದೇವಾಂಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Devang - ದೇವಾಂಗ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Rajput - ರಜಪೂತ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Andi - ಆಂಡಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Hatgar/Hatga - ಹಟಗಾರ್/ಹಟಗಾ", category: "2A", nigama: "Devraj Urs" },
  { name: "Andipandaram - ಆಂಡಿಪಂಡಾರಂ", category: "2A", nigama: "Devraj Urs" },
  { name: "Bandhi - ಬಾಂಧಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Bolahallala - ಬೋಲಹಳ್ಳಾಲ", category: "2A", nigama: "Devraj Urs" },
  { name: "Ballala - ಬಲ್ಲಾಳ", category: "2A", nigama: "Devraj Urs" },
  { name: "Bhatiyal - ಭಟಿಯಾಲ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Hatgara - ಹಟಗಾ", category: "2A", nigama: "Devraj Urs" },
  { name: "Bhattiya - ಭಟ್ಟಿಯಾ", category: "2A", nigama: "Devraj Urs" },
  { name: "Neyge - ನೇಯ್ದೆ", category: "2A", nigama: "Devraj Urs" },
  { name: "Chakkan - ಚಕ್ಕನ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Kuruhina Shetti - ಕುರುಹಿನ ಶೆಟ್ಟಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Dogra - ಡೋಗ್ರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Gulli - ಗುಳ್ಳಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Bili Magga - ಬಿಳಿ ಮಗ್ಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Togata/Togataru/Togateg - ತೊಗಟ/ತೊಗಟರು/ತೊಗಟೆಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Togataveera/Togatager - ತೊಗಟವೀರ/ತೊಗಟಗೇರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Saadru/Hindu Saadru - ಸಾದರು/ಹಿಂದೂ ಸಾದರು", category: "2A", nigama: "Devraj Urs" },
  { name: "Saadumat/Sadkula/Sada - ಸಾದುಮತ/ಸಾದಕುಲ/ಸಾದ", category: "2A", nigama: "Devraj Urs" },
  { name: "Sadhugouda/Sadugoudar/Sadar - ಸಾಧುಗೌಡ/ಸಾದುಗೌಡರ್/ಸಾದರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Togataveera Kruti/Togat - ತೊಗಟವೀರ ಕೃತಿಯ/ತೊಗಟ", category: "2A", nigama: "Devraj Urs" },
  { name: "Saadari/Sadaragouda - ಸಾದರಿ/ಸಾದರಗೌಡ", category: "2A", nigama: "Devraj Urs" },
  { name: "Soniga - ಸೋಣಿಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Jankhan - ಜಂಖಾನ", category: "2A", nigama: "Devraj Urs" },
  { name: "Jetti/Jatti - ಜೆಟ್ಟಿ/ಜಟ್ಟಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Mallaru Malla Kshatriya - ಮಲ್ಲಾರು ಮಲ್ಲ ಕ್ಷತ್ರಿಯ", category: "2A", nigama: "Devraj Urs" },
  { name: "Mushtiga - ಮುಷ್ಠಿಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Airi - ಅವಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kalavanti - ಕಲಾವಂತಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Bhogam/Telugu - ಭೋಗಂ/ತೆಲುಗ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kanakan - ಕನಕನ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Kanakar - ಕನಕ", category: "2A", nigama: "Devraj Urs" },
  { name: "Karunika - ಕರುಣಿಕ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kotegara - ಕೋಟೆಗಾರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Koteeyar - ಕೋಟೆಯಾ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kothati - ಕೊಥಾಟಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kottegara - ಕೊಟ್ಟೇಗಾರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Pathegar - ಪಟೇಗಾ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kotteyar - ಕೊಟ್ಟೇಯಾರ", category: "2A", nigama: "Devraj Urs" },
  { name: "Patthekari - ಪಟ್ಟೇಕಾರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kumar Kshatriya - ಕುಮಾರ ಕ್ಷತ್ರಿಯ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kumar Panth/Komar Panth - ಕುಮಾರ ಪಂಥ್/ಕೊಮಾರ್ ಪಂತ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Somavamsha Sahasrarjuna - ಸೋಮವಂಶ ಸಹಾಸ್ರಾರ್ಜುನ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kshatriya - ಕ್ಷತ್ರಿಯ", category: "2A", nigama: "Devraj Urs" },
  { name: "Theli - ತೇಲಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Rama Kshatriya - ರಾಮ ಕ್ಷತ್ರಿಯ", category: "2A", nigama: "Devraj Urs" },
  { name: "Ramraj Kshatriya - ರಾಮರಾಜ ಕ್ಷತ್ರಿಯ", category: "2A", nigama: "Devraj Urs" },
  { name: "Serugara (Uttara Kannada) - ಸೇರುಗಾರ (ಉತ್ತರ ಕನ್ನಡ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Sarvagaar(Dakshina Kannada) - ಸರ್ವಗಾ (ದಕ್ಷಿಣ ಕನ್ನಡ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Kote Kshatriya - ಕೋಟೆ ಕ್ಷತ್ರಿಯ", category: "2A", nigama: "Devraj Urs" },
  { name: "Kshatriya: Kshatri - ಕ್ಷತ್ರಿಯ : ಕ್ಷತ್ರಿ", category: "2A", nigama: "Devraj Urs" },
  { name: "Malava - ಮಲವ", category: "2A", nigama: "Devraj Urs" },
  { name: "Maleya - ಮಲೆಯ", category: "2A", nigama: "Devraj Urs" },
  { name: "Aaryen - ಆರನ್", category: "2A", nigama: "Devraj Urs" },
  { name: "Raju Kshatriya - ರಾಜು ಕ್ಷತ್ರಿಯ", category: "2A", nigama: "Devraj Urs" },
  { name: "Raju - ರಾಜು", category: "2A", nigama: "Devraj Urs" },
  { name: "Rajuwar/Rajavar/Rajeva - ರಾಜುವರ್/ರಾಜವರ್/ ರಾಜೀವಾ", category: "2A", nigama: "Devraj Urs" },
  { name: "Somavamsha Kshatriya - ಸೋಮವಂಶ ಕ್ಷತ್ರಿಯ", category: "2A", nigama: "Devraj Urs" },
  { name: "Sthaanika - ಸ್ಥಾನಿಕ", category: "2A", nigama: "Devraj Urs" },
  { name: "Tulu - ತುಳು", category: "2A", nigama: "Devraj Urs" },
  { name: "Tulva - ತುಳುವ", category: "2A", nigama: "Devraj Urs" },
  { name: "Ushnama (Dharwad, Belagavi, Vijayapura, and Gadag districts) - ಉಷ್ಣಮ (ಧಾರವಾಡ, ಬೆಳಗಾವಿ, ವಿಜಯಪುರ, ಮತ್ತು ಗದಗ ಜಿಲ್ಲೆಗಳು)", category: "2A", nigama: "Devraj Urs" },
] as const;

export const CASTE_NAMES = CASTES.map((c) => c.name);

export const CASTE_CATEGORIES = Array.from(new Set(CASTES.map((c) => c.category))).filter((cat) => cat !== "nan" && cat !== "NaN");

export const NIGAMAS = Array.from(new Set(CASTES.map((c) => c.nigama))).filter((nig) => nig !== "nan" && nig !== "NaN");
