export type CasteEntry = { name: string; category: string; nigama: string };

export const CASTES: readonly CasteEntry[] = [
  { name: "Ganiga (ಗಾಣಿಗ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Teli (ತೇಲಿ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Gandla (ಗಾಂಡ್ಲ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Vaniyan (ವನಿಯನ್)", category: "2A", nigama: "Devraj Urs" },
  { name: "Jyothi Nagar/Jyothi Nagar Vyshya (ಜ್ಯೋತಿನಗರ/ಜ್ಯೋತಿನಗರ ವ್ಯಶ್ಯ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Eediga (ಈಡಿಗ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Bhandari (ಭಂಡಾರಿ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Belbad (ಬೆಲ್ಬದ್)", category: "2A", nigama: "Devraj Urs" },
  { name: "Billava (ಬಿಲ್ಲವ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Pujari (ಪೂಜಾರಿ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Divara (ದೀವರ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Hala Kshatriya (ಹಾಲ ಕ್ಷತ್ರಿಯ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Desh Bhandari (ದೇಶ ಭಂಡಾರಿ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Devara (ದೇವರ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Devara Makkalu / Deevara Makkalu (ದೇವರ ಮಕ್ಕಳು/ದೀವರ ಮಕ್ಕಳು)", category: "2A", nigama: "Devraj Urs" },
  { name: "Aeliga (ಎಳಿಗ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Aelava (ಎಳವ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Helava (ಹೆಳವ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Gamalla (ಗಾಮಲ್ಲ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Goundla (ಗೌಂಡ್ಲ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Hale Paikaru (ಹಳೇ ಪೈಕರು)", category: "2A", nigama: "Devraj Urs" },
  { name: "Hale Pike (ಹಳೇ ಪೈಕ್)", category: "2A", nigama: "Devraj Urs" },
  { name: "Illavan (ಇಲ್ಲಾವನ್)", category: "2A", nigama: "Devraj Urs" },
  { name: "Kalal (ಕಲಾಲ್)", category: "2A", nigama: "Devraj Urs" },
  { name: "Malayali Billava (ಮಲಯಾಳಿ ಬಿಲ್ಲವ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Naadar (ನಾಡರ್)", category: "2A", nigama: "Devraj Urs" },
  { name: "Naamadhari (ನಾಮಧಾರಿ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Thiyaan/Thiyya (ಥಿಯಾನ್/ಥಿಯ್ಯ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Iliga (ಇಳಿಗ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Gondla (ಗೊಂಡ್ಲ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Tiyan/Thiyyaan (ತಿಯನ್/ಥಿಯ್ಯಾನ್)", category: "2A", nigama: "Devraj Urs" },
  { name: "Daevanga (ದೇವಾಂಗ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Daevang (ದೇವಾಂಗ್)", category: "2A", nigama: "Devraj Urs" },
  { name: "Koshti (ಕೋಷ್ಠಿ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Hatagaar (ಹಟಗಾರ್/ಹಟಗಾರ್)", category: "2A", nigama: "Devraj Urs" },
  { name: "Jade (ಜೇಡ್)", category: "2A", nigama: "Devraj Urs" },
  { name: "Winkaar (ವಿಂಕಾರ್)", category: "2A", nigama: "Devraj Urs" },
  { name: "Juloohi (ಜುಲೋಹಿ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Halkaar (ಹಲ್ಕಾರ್)", category: "2A", nigama: "Devraj Urs" },
  { name: "Hatagaar (ಹಟಗಾರ್)", category: "2A", nigama: "Devraj Urs" },
  { name: "Naeyke (ನೇಯ್ದೆ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Kuruhina Shetty (ಕುರುಹಿನ ಶೆಟ್ಟಿ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Kurni (ಕುರಿ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Bili Magga (ಬಿಳಿಮಗ್ಗ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Togata/ Toogataru/ Togatiga (ತೊಗಟ/ತೊಗಟರು/ತೊಗಟಿಗ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Togataweera/Togatagera (ತೊಗಟವೀರ/ತೊಗಟಗೇರ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Togatavira Kshatriya/Togaja Pushpanjali (ತೊಗಟವೀರ ಕ್ಷತ್ರಿಯ/ತೊಗಜ ಪುಷ್ಪಾಂಜಲಿ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Sooniga (ಸೋಣಿಗ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Jankhana (ಜಂಖಾನ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Airi (ಐರಿ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Avir (ಅವಿರೋ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Saale: Pattasaalae (ಸಾಲೆ:ಪಟ್ಟಸಾಲೆ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Padmasaalae/Padmashaali/Padmasaali (ಪದ್ಮಸಾಲೆ/ಪದ್ಮಶಾಲಿ/ ಪದ್ಮಸಾಲಿ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Saali/Pattasaali (ಸಾಲಿ/ಪಟ್ಟಸಾಲಿ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Kaikoolan/Sengunder (ಕೈಕೋಳನ್/ಸೆಂಗುಂದರ್‌)", category: "2A", nigama: "Devraj Urs" },
  { name: "Neykaar (ನೇಯ್ಕಾರ್)", category: "2A", nigama: "Devraj Urs" },
  { name: "Jaadar (ಜಾಡರ್)", category: "2A", nigama: "Devraj Urs" },
  { name: "Chandra (ಚಾಂದ್ರ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Svakulasali/Svakulsali (ಸ್ವಕುಳಸಾಳಿ/ಸ್ವಕುಳಸಾಳೆ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Kumbar (ಕುಂಬಾರ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Chakrasali (ಚಕ್ರಸಾಲಿ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Gunga (ಗುಣಗ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Ganagi (ಗಣಗಿ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Koyava (ಕೊಯವ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Kula (ಕುಲ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Kulaala (ಕುಲಾಲ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Kumbaar (ಕುಂಬಾರ್)", category: "2A", nigama: "Devraj Urs" },
  { name: "kumbaarda (ಕುಂಬಾರ್ಡ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Kummaara (ಕುಮ್ಮಾರ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Kusavan (ಕುಸವನ್)", category: "2A", nigama: "Devraj Urs" },
  { name: "Maulya (ಮೂಲ್ಯ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Sajjana Kumbaara (ಸಜ್ಜನ ಕುಂಬಾರ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Khumaara (ಖುಮಾರ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Kumbhara (ಕುಂಭಾರ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Khumbhaara (ಖುಂಭಾರ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Kulaalar (ಕುಲಾಲರ್)", category: "2A", nigama: "Devraj Urs" },
  { name: "Tigala (ತಿಗಲ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Agnivamsha (ಅಗ್ನಿವಂಶ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Agnivanni (ಅಗ್ನಿವನ್ನಿ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Agnikulakshatriya (ಅಗ್ನಿಕುಲಕ್ಷತ್ರಿಯ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Dharmaraja Kaapu (ಧರ್ಮರಾಜ ಕಾಪು)", category: "2A", nigama: "Devraj Urs" },
  { name: "Palli (ಪಳ್ಳಿ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Shambhukulakshatriya (ಶಂಭುಕುಲ ಕ್ಷತ್ರಿಯ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Tigala (ತಿಗಳ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Vanniyar (ವನ್ನಿಯರ್)", category: "2A", nigama: "Devraj Urs" },
  { name: "Vannikulakshatriya (ವನ್ನಿಕುಲಕ್ಷತ್ರಿಯ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Tiglar (ತಿಗ್ಗರ್)", category: "2A", nigama: "Devraj Urs" },
  { name: "Kuroovan (ಕುರೋವನ್)", category: "2A", nigama: "Devraj Urs" },
  { name: "Hadapada (ಹಡಪದ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Huvaadiga (ಹೂವಾಡಿಗ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Hugaar (ಹುಗಾರ್)", category: "2A", nigama: "Devraj Urs" },
  { name: "Huugaar (ಹೂಗಾರ್)", category: "2A", nigama: "Devraj Urs" },
  { name: "Malgaar (ಮಾಲಗಾರ್)", category: "2A", nigama: "Devraj Urs" },
  { name: "Maali (ಮಾಲಿ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Moolmali (ಮೂಲ್‌ಮಾಲಿ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Phulmali (ಫುಲ್‌ಮಾಲಿ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Phulaari (ಫುಲಾರಿ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Phalaari (ಫಲಾರಿ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Jeer (ಜಿರಾ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Balija (ಬಲಿಜ)", category: "3A", nigama: "Devraj Urs" },
  { name: "Balajiga/Banajiga/Gowdabanajiga (ಬಲಜಿಗ/ಬಣಜಿಗ/ಗೌಡಬಣಜಿಗ)", category: "3A", nigama: "Devraj Urs" },
  { name: "Naydu (ನಾಯ್ಡು)", category: "3A", nigama: "Devraj Urs" },
  { name: "Telaga Balija/Telaga Banajiga (ತೆಲಗ ಬಲಿಜ/ತೆಲಗ ಬಣಜಿಗ)", category: "3A", nigama: "Devraj Urs" },
  { name: "Shetty Balija/Shetty Banajiga/Banajiga Shetty (ಶೆಟ್ಟಿ ಬಲಿಜ/ಶೆಟ್ಟಿ ಬಣಜಿಗ/ಬಣಜಿಗ ಶೆಟ್ಟಿ)", category: "3A", nigama: "Devraj Urs" },
  { name: "Dasara Balija/Dasare Baljiga (ದಾಸರ ಬಲಿಜ/ದಾಸರೆ ಬಲಜಿಗ)", category: "3A", nigama: "Devraj Urs" },
  { name: "Dasara Banajiga/Daasa Banajiga (ದಾಸರ ಬಣಜಿಗ/ದಾಸ ಬಣಜಿಗ)", category: "3A", nigama: "Devraj Urs" },
  { name: "Cusban (ಕಸ್ಟನ್)", category: "3A", nigama: "Devraj Urs" },
  { name: "Munnur/Munnar/Munnur Kaup (ಮುನ್ನೂರ/ಮುನ್ನಾರ್/ಮುನ್ನೂರ್ ಕಾಪು)", category: "3A", nigama: "Devraj Urs" },
  { name: "Balegara/Bale Banajiga/Bale Baljiga (ಬಳೆಗಾರ/ಬಳೆ ಬಣಜಿಗ/ಬಳೆ ಬಲಜಿಗ)", category: "3A", nigama: "Devraj Urs" },
  { name: "Bale Chetti/Banegara (ಬಳೆ ಚೆಟ್ಟಿ/ ಬಣಗಾರ)", category: "3A", nigama: "Devraj Urs" },
  { name: "Reddy (Balija) (ರೆಡ್ಡಿ (ಬಲಿಜ))", category: "3A", nigama: "Devraj Urs" },
  { name: "Janappan (ಜನಪ್ಪನ್)", category: "3A", nigama: "Devraj Urs" },
  { name: "Uppara (Balija) (ಉಪ್ಪಾರ (ಬಲಿಜ))", category: "3A", nigama: "Devraj Urs" },
  { name: "Tulaeru (Balija) (ತುಲೇರು (ಬಲಿಜ))", category: "3A", nigama: "Devraj Urs" },
  { name: "Kodagaru (ಕೊಡಗರು)", category: "3A", nigama: "Devraj Urs" },
  { name: "Maedara (ಮೇದರ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Battar (ಬಟ್ಟಿರೋ)", category: "1", nigama: "Devraj Urs" },
  { name: "Burned (ಬರ್ನೆಡ್)", category: "1", nigama: "Devraj Urs" },
  { name: "Gauriga (ಗೌರಿಗ)", category: "1", nigama: "Devraj Urs" },
  { name: "Gauv Rigga (ಗೌವ್ ರಿಗ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Gauri (ಗೌರಿ)", category: "1", nigama: "Devraj Urs" },
  { name: "Gauri Marata (ಗೌರಿ ಮರಾಠ)", category: "1", nigama: "Devraj Urs" },
  { name: "Gauriga (ಗೌರಿಗ)", category: "1", nigama: "Devraj Urs" },
  { name: "Maedari (ಮೇದರಿ)", category: "2A", nigama: "Devraj Urs" },
  { name: "Burud (ಬುರುಡ್)", category: "1", nigama: "Devraj Urs" },
  { name: "Kadugolla (ಕಾಡುಗೊಲ್ಲ)", category: "1", nigama: "Kadugolla" },
  { name: "uppara (ಉಪ್ಪಾರ)", category: "2A", nigama: "Uppara Development" },
  { name: "Belder (ಬೆಲ್ಡರ್)", category: "2A", nigama: "Uppara Development" },
  { name: "Chunaar (ಚುನಾರ್)", category: "2A", nigama: "Uppara Development" },
  { name: "Gaawaadi (ಗಾವಾಡಿ)", category: "2A", nigama: "Uppara Development" },
  { name: "Kallu Kutiga Uppara (ಕಲ್ಲು ಕುಟಿಗ ಉಪ್ಪಾರ)", category: "2A", nigama: "Uppara Development" },
  { name: "Loonaari (ಲೋನಾರಿ)", category: "2A", nigama: "Uppara Development" },
  { name: "Maelu Sakkareyavaru (ಮೇಲು ಸಕ್ಕರೆಯವರು)", category: "2A", nigama: "Uppara Development" },
  { name: "Maelu Sakkare (ಮೇಲು ಸಕ್ಕರೆ)", category: "2A", nigama: "Uppara Development" },
  { name: "Naamada Uppaara (ನಾಮದ ಉಪ್ಪಾರ)", category: "2A", nigama: "Uppara Development" },
  { name: "Padit / Padti (ಪಡಿತ್ / ಪಡ್ತಿ)", category: "2A", nigama: "Uppara Development" },
  { name: "Padithi (ಪಡಿತಿ)", category: "2A", nigama: "Uppara Development" },
  { name: "Paadi (ಪಾಡಿ)", category: "2A", nigama: "Uppara Development" },
  { name: "Sagara (ಸಗರ)", category: "2A", nigama: "Uppara Development" },
  { name: "Sunnagaara (ಸುಣ್ಣಗಾರ)", category: "2A", nigama: "Uppara Development" },
  { name: "Sunna Uppaara (ಸುಣ್ಣ ಉಪ್ಪಾರ)", category: "2A", nigama: "Uppara Development" },
  { name: "Uppaliga (ಉಪ್ಪಳಿಗ)", category: "2A", nigama: "Uppara Development" },
  { name: "Uppaligashetti (ಉಪ್ಪಳಿಗಶೆಟ್ಟಿ)", category: "2A", nigama: "Uppara Development" },
  { name: "Uppalian (ಉಪ್ಪಳಿಯನ್)", category: "2A", nigama: "Uppara Development" },
  { name: "Uppeara (ಉಪ್ಪೇರ)", category: "2A", nigama: "Uppara Development" },
  { name: "Yakalaara (ಯಕಲಾರ)", category: "2A", nigama: "Uppara Development" },
  { name: "Ekkali (ಎಕ್ಕಲಿ)", category: "2A", nigama: "Uppara Development" },
  { name: "Goundi (ಗೌಂದಿ)", category: "2A", nigama: "Uppara Development" },
  { name: "Besta (ಬೆಸ್ತ)", category: "2A", nigama: "Ambiga Development" },
  { name: "Ambiga/Ambi (ಅಂಬಿಗ/ಅಂಬಿ)", category: "2A", nigama: "Ambiga Development" },
  { name: "Baarika (ಬಾರಿ/ಬಾರಿಕ)", category: "2A", nigama: "Ambiga Development" },
  { name: "Bester (ಬೆಸ್ತರ್)", category: "2A", nigama: "Ambiga Development" },
  { name: "Bhoi (ಭೋಯಿ)", category: "2A", nigama: "Ambiga Development" },
  { name: "Rajaboi (ರಾಜಬೊಯಿ)", category: "2A", nigama: "Ambiga Development" },
  { name: "Bunde-Beshtar (ಬುಂಡೆ - ಬೆಸ್ಥರ್)", category: "2A", nigama: "Ambiga Development" },
  { name: "Dalti (ದಾಲ್ಟಿ)", category: "2A", nigama: "Ambiga Development" },
  { name: "dawat (ದಾವತ್)", category: "2A", nigama: "Ambiga Development" },
  { name: "Gabbit (ಗಬಿಟ್)", category: "2A", nigama: "Ambiga Development" },
  { name: "Galadkonkani (ಗಲಾಡಕೊಂಕಣಿ)", category: "2A", nigama: "Ambiga Development" },
  { name: "Ganga makkalu (ಗಂಗಮಕ್ಕಳು)", category: "2A", nigama: "Ambiga Development" },
  { name: "Gangakula (ಗಂಗಾಕುಲ)", category: "2A", nigama: "Ambiga Development" },
  { name: "Gangamata (ಗಂಗಾಮತ)", category: "2A", nigama: "Ambiga Development" },
  { name: "Gangamastha (ಗಂಗಾಮತಸ್ಥ)", category: "2A", nigama: "Ambiga Development" },
  { name: "Gangaputra (ಗಂಗಾಪುತ್ರ)", category: "2A", nigama: "Ambiga Development" },
  { name: "Gaurimata (ಗೌರಿಮತ)", category: "2A", nigama: "Ambiga Development" },
  { name: "Bunde-Besta/Gunde Besta (ಬುಂಡೆ-ಬೆಸ್ತ/ಗುಂಡೆ ಬೆಸ್ತ)", category: "2A", nigama: "Ambiga Development" },
  { name: "Harakantra (ಹರಕಂತ್ರ)", category: "2A", nigama: "Ambiga Development" },
  { name: "Jalagaara (ಜಲಗಾರ)", category: "2A", nigama: "Ambiga Development" },
  { name: "Kabbera / Kabbear (ಕಬ್ಬೇರ / ಕಬ್ಬರ್)", category: "2A", nigama: "Ambiga Development" },
  { name: "Kabbaliga (ಕಬ್ಬಲಿಗ)", category: "2A", nigama: "Ambiga Development" },
  { name: "Kabbili (ಕಬ್ಬಿಲಿ)", category: "2A", nigama: "Ambiga Development" },
  { name: "Kahar (ಕಹರ್)", category: "2A", nigama: "Ambiga Development" },
  { name: "Kharvi / Konkan Kharvi (ಖಾರ್ವಿ /ಕೊಂಕಣ ಖಾರ್ವಿ)", category: "2A", nigama: "Ambiga Development" },
  { name: "Koli (ಕೋಳಿ)", category: "2A", nigama: "Ambiga Development" },
  { name: "Koli Mahadev (ಕೋಳಿ ಮಹದೇವ್)", category: "2A", nigama: "Ambiga Development" },
  { name: "Mudder (ಮಡ್ಡರ್)", category: "2A", nigama: "Ambiga Development" },
  { name: "Meenagar (ಮೀನಗಾ‌ರ್)", category: "2A", nigama: "Ambiga Development" },
  { name: "Mogaveer (ಮೊಗವೀರ)", category: "2A", nigama: "Ambiga Development" },
  { name: "Mogaer (ಮೊಗೇರ್)", category: "2A", nigama: "Ambiga Development" },
  { name: "Mukkawan (ಮುಕ್ಕವಾನ್)", category: "2A", nigama: "Ambiga Development" },
  { name: "Pariwara (ಪರಿವಾರ)", category: "2A", nigama: "Ambiga Development" },
  { name: "Seveyar (ಸಿವಿಯರ್)", category: "2A", nigama: "Ambiga Development" },
  { name: "Sunagaara (ಸುಣಗಾರ)", category: "2A", nigama: "Ambiga Development" },
  { name: "Tureya (ತೊರೆಯ)", category: "2A", nigama: "Ambiga Development" },
  { name: "Pagi (ಪಾಗಿ)", category: "2A", nigama: "Ambiga Development" },
  { name: "Jogi (ಜೋಗಿ)", category: "1", nigama: "Alemari mathu Are Alemari" },
  { name: "Joshi Sada Joshi (ಜೋಶಿ ಸದ ಜೋಶಿ)", category: "1", nigama: "Alemari mathu Are Alemari" },
  { name: "Kashikapaddi (ಕಾಶಿಕಪಾಡಿ)", category: "1", nigama: "Alemari mathu Are Alemari" },
  { name: "Katabu (ಕಟಬು)", category: "1", nigama: "Alemari mathu Are Alemari" },
  { name: "Kel Kari (ಕೆಲ್‌ ಕಾರಿ)", category: "1", nigama: "Alemari mathu Are Alemari" },
  { name: "Killekyathas (ಕಿಳ್ಳೆಕ್ಯಾತಸ್)", category: "1", nigama: "Alemari mathu Are Alemari" },
  { name: "Kolathi (ಕೋಲಾತಿ)", category: "1", nigama: "Alemari mathu Are Alemari" },
  { name: "Masani Yogi (ಮಸನಿಯ ಯೋಗಿ)", category: "1", nigama: "Alemari mathu Are Alemari" },
  { name: "Nandiwala-Joshi-Ghondal- Pul Malli (ನಂದಿವಾಲ-ಜೋಶಿ-ಘೋಂಡಳ್- ಪುಲ್ ಮಲ್ಲಿ)", category: "1", nigama: "Alemari mathu Are Alemari" },
  { name: "Nathapachithi, Dauri Gosavi (ನಾಥಪಚಿಥಿ, ಡೌರಿಗೋಸಾವಿ)", category: "1", nigama: "Alemari mathu Are Alemari" },
  { name: "Neer Shikari (ನೀರ್‌ ಶಿಕಾರಿ)", category: "1", nigama: "Alemari mathu Are Alemari" },
  { name: "Pangul (ಪಂಗುಲ್)", category: "1", nigama: "Alemari mathu Are Alemari" },
  { name: "Pichaguntala (ಪಿಚಗುಂಟಲ)", category: "1", nigama: "Alemari mathu Are Alemari" },
  { name: "Sansiya (ಸನ್‌ಸಿಯ)", category: "1", nigama: "Alemari mathu Are Alemari" },
  { name: "Sarnia (ಸರನಿಯ)", category: "1", nigama: "Alemari mathu Are Alemari" },
  { name: "Sarodi (ಸರೊಡಿ)", category: "1", nigama: "Alemari mathu Are Alemari" },
  { name: "Shikkaligarh (ಶಿಕ್ಕಲಿಗಾರ್‌)", category: "1", nigama: "Alemari mathu Are Alemari" },
  { name: "Tirumali (ತಿರುಮಲಿ)", category: "1", nigama: "Alemari mathu Are Alemari" },
  { name: "Padi (ಪಡಿ)", category: "1", nigama: "Alemari mathu Are Alemari" },
  { name: "Vagri (ವಗ್ರಿ)", category: "1", nigama: "Alemari mathu Are Alemari" },
  { name: "wydu (ವೈಡು)", category: "1", nigama: "Alemari mathu Are Alemari" },
  { name: "Vasudev (ವಾಸುದೇವ್)", category: "1", nigama: "Alemari mathu Are Alemari" },
  { name: "Vir (ವಿರೋ)", category: "1", nigama: "Alemari mathu Are Alemari" },
  { name: "Agasa (ಅಗಸ)", category: "Veerashaiva Lingayata (3B)", nigama: "Madivala Machideva" },
  { name: "Chakala (ಚಕಲ)", category: "2A", nigama: "Madivala Machideva" },
  { name: "Dhobi (ಧೋಬಿ)", category: "2A", nigama: "Madivala Machideva" },
  { name: "Madiwala (ಮಡಿವಾಳ)", category: "2A", nigama: "Madivala Machideva" },
  { name: "Mannan (ಮನ್ನನ್)", category: "2A", nigama: "Madivala Machideva" },
  { name: "Parit (ಪರಿತ್)", category: "2A", nigama: "Madivala Machideva" },
  { name: "Rajaka (ರಾಜಕ)", category: "2A", nigama: "Madivala Machideva" },
  { name: "Sakala (ಸಕಲ)", category: "2A", nigama: "Madivala Machideva" },
  { name: "Wannan (ವನ್ನನ್)", category: "2A", nigama: "Madivala Machideva" },
  { name: "Welluteddan (ವೆಲ್ಲು ತೇಡನ್)", category: "2A", nigama: "Madivala Machideva" },
  { name: "Sakalavaaddu (ಸಾಕಲವಾಡು)", category: "2A", nigama: "Madivala Machideva" },
  { name: "Pariyala (South Kannada and Udupi District) (ಪರಿಯಾಳ (ದಕ್ಷಿಣ ಕನ್ನಡ ಮತ್ತು ಉಡುಪಿ ಜಿಲ್ಲೆ))", category: "2A", nigama: "Savita Samaaja" },
  { name: "Ambattan (ಅಂಬಟ್ಟನ್)", category: "2A", nigama: "Savita Samaaja" },
  { name: "Bajantri (ಬಜಂತ್ರಿ)", category: "Veerashaiva Lingayata (3B)", nigama: "Savita Samaaja" },
  { name: "Bhanddari (ಬಂಡಾರಿ)", category: "2A", nigama: "Savita Samaaja" },
  { name: "Chauriya (ಚೌರಿಯ)", category: "2A", nigama: "Savita Samaaja" },
  { name: "Kavutian (ಕವುಟಿಯನ್)", category: "2A", nigama: "Savita Samaaja" },
  { name: "Kelasi (ಕೆಲಸಿ)", category: "2A", nigama: "Savita Samaaja" },
  { name: "Kshaurika (ಕ್ಷೌರಿಕ)", category: "Veerashaiva Lingayata (3B)", nigama: "Savita Samaaja" },
  { name: "Kshourad (ಕ್ಷೌರದ್)", category: "2A", nigama: "Savita Samaaja" },
  { name: "Mahale (ಮಹಾಲೆ)", category: "2A", nigama: "Savita Samaaja" },
  { name: "Mangala (ಮಂಗಳ)", category: "2A", nigama: "Savita Samaaja" },
  { name: "Melagar (ಮೇಲಗಾರ)", category: "2A", nigama: "Savita Samaaja" },
  { name: "Naddiga (ನಾಡಿಗ)", category: "2A", nigama: "Savita Samaaja" },
  { name: "Napita (ನಾಪಿತ)", category: "2A", nigama: "Savita Samaaja" },
  { name: "Navalig (ನವಲಿಗ್)", category: "2A", nigama: "Savita Samaaja" },
  { name: "Navi (ನಾವಿ)", category: "2A", nigama: "Savita Samaaja" },
  { name: "Nayanaja Kshatriya (ನಯನಜ ಕ್ಷತ್ರಿ)", category: "2A", nigama: "Savita Samaaja" },
  { name: "Nhavi (ನಾವಿ)", category: "2A", nigama: "Savita Samaaja" },
  { name: "Vajantri (North Kannada District) (ವಾಜಾಂತ್ರಿ (ಉತ್ತರ ಕನ್ನಡ ಜಿಲ್ಲೆ))", category: "2A", nigama: "Savita Samaaja" },
  { name: "Savita (ಸವಿತ)", category: "2A", nigama: "Savita Samaaja" },
  { name: "Nayanaja Kshatriya (ನಯನಜ ಕ್ಷತ್ರಿ)", category: "2A", nigama: "Savita Samaaja" },
  { name: "Naadiga (ನಾಡಿಗ)", category: "2A", nigama: "Savita Samaaja" },
  { name: "Kshourik (ಕ್ಷೌರಿಕ್)", category: "2A", nigama: "Savita Samaaja" },
  { name: "Kshourika (ಕ್ಷೌರಿಕ)", category: "2A", nigama: "Savita Samaaja" },
  { name: "Vishwakarma (ವಿಶ್ವಕರ್ಮ)", category: "2A", nigama: "Vishwakarma" },
  { name: "Aachaari (ಆಚಾರಿ)", category: "2A", nigama: "Vishwakarma" },
  { name: "Akkasaali (ಅಕ್ಕಸಾಲಿ)", category: "2A", nigama: "Vishwakarma" },
  { name: "Ausaali (ಔಸಾಲಿ)", category: "2A", nigama: "Vishwakarma" },
  { name: "Badiger (ಬಡಿಗರ್)", category: "2A", nigama: "Vishwakarma" },
  { name: "Badiwadda (ಬಡಿವಾಡ್ಡ)", category: "2A", nigama: "Vishwakarma" },
  { name: "Bailu Akkasali (ಬೈಲು ಅಕ್ಕಸಾಲಿ)", category: "2A", nigama: "Vishwakarma" },
  { name: "Bailu Kammaara (ಬೈಲು ಕಮ್ಮಾರ)", category: "2A", nigama: "Vishwakarma" },
  { name: "Bogara (ಬೋಗಾರ)", category: "2A", nigama: "Vishwakarma" },
  { name: "Chappegar (ಚಪ್ಪೇಗಾರ್)", category: "2A", nigama: "Vishwakarma" },
  { name: "Chaarodi (ಚಾರೋಡಿ)", category: "2A", nigama: "Vishwakarma" },
  { name: "Konkani Aachaara (ಕೊಂಕಣಿ ಆಚಾರ)", category: "2A", nigama: "Vishwakarma" },
  { name: "Dyvagnya Bhramana (ದೈವಜ್ಞಾಬ್ರಾಹ್ಮಣ)", category: "2A", nigama: "Vishwakarma" },
  { name: "Gejjegara (ಗೆಜ್ಜೆಗಾರ)", category: "2A", nigama: "Vishwakarma" },
  { name: "Kambar (ಕಂಬಾರ್)", category: "2A", nigama: "Vishwakarma" },
  { name: "Kammalan (ಕಮ್ಮಾಲನ್)", category: "2A", nigama: "Vishwakarma" },
  { name: "Kammaara (ಕಮ್ಮಾರ)", category: "2A", nigama: "Vishwakarma" },
  { name: "Kansala (ಕಂಸಾಳ)", category: "Veerashaiva Lingayata (3B)", nigama: "Vishwakarma" },
  { name: "Kansan (ಕಂಸನ್)", category: "2A", nigama: "Vishwakarma" },
  { name: "Kanchagarh (ಕಂಚಗಾರ್)", category: "2A", nigama: "Vishwakarma" },
  { name: "Kanchora (ಕಂಚೋರ)", category: "2A", nigama: "Vishwakarma" },
  { name: "Bailpatar (ಬೈಲ್‌ಪತರ್‌)", category: "2A", nigama: "Vishwakarma" },
  { name: "Kanchori (ಕಂಚೋರಿ)", category: "2A", nigama: "Vishwakarma" },
  { name: "Kanchugaara (ಕಂಚುಗಾರ)", category: "2A", nigama: "Vishwakarma" },
  { name: "Kansara (ಕಂಸಾರ)", category: "2A", nigama: "Vishwakarma" },
  { name: "Lohar (ಲೋಹಾರ್)", category: "2A", nigama: "Vishwakarma" },
  { name: "Mesta (ಮೆಸ್ತ)", category: "2A", nigama: "Vishwakarma" },
  { name: "Panchal (ಪಂಚಾಲ್)", category: "2A", nigama: "Vishwakarma" },
  { name: "Pathar (ಪತ್ತರ್)", category: "2A", nigama: "Vishwakarma" },
  { name: "Sohgar (ಸೋಹಗಾರ್)", category: "2A", nigama: "Vishwakarma" },
  { name: "Silchi (ಸಿಲ್ಚಿ)", category: "2A", nigama: "Vishwakarma" },
  { name: "Kasar (ಕಸಾರ್)", category: "2A", nigama: "Vishwakarma" },
  { name: "Sonar (ಸೋನಾರ್)", category: "2A", nigama: "Vishwakarma" },
  { name: "Soni (ಸೋನಿ)", category: "2A", nigama: "Vishwakarma" },
  { name: "Sutar (ಸುತಾರ್)", category: "2A", nigama: "Vishwakarma" },
  { name: "Tasehan (ತಸೆಹಾನ್)", category: "2A", nigama: "Vishwakarma" },
  { name: "VishwaBrahman (ವಿಶ್ವಬ್ರಾಹ್ಮಣ)", category: "2A", nigama: "Vishwakarma" },
  { name: "Thattan (ಥಟ್ಟನ್)", category: "2A", nigama: "Vishwakarma" },
  { name: "Aksali (ಅಕ್ಸಾಲಿ)", category: "2A", nigama: "Vishwakarma" },
  { name: "Kamsali (ಕಂಸಾಲ್)", category: "2A", nigama: "Vishwakarma" },
  { name: "Badagi (ಬಡಗಿ)", category: "2A", nigama: "Vishwakarma" },
  { name: "Vokkaliga (ಒಕ್ಕಲಿಗ)", category: "Vokkaliga", nigama: "Vokkaliga" },
  { name: "Vakkaliga (ವಕ್ಕಲಿಗ)", category: "Vokkaliga", nigama: "Vokkaliga" },
  { name: "Sarpa Vakkaliga (ಸರ್ಪ ಒಕ್ಕಲಿಗ)", category: "Vokkaliga", nigama: "Vokkaliga" },
  { name: "Hallikar Vokkaliga (ಹಳ್ಳಿಕಾರ್ ಒಕ್ಕಲಿಗ)", category: "Vokkaliga", nigama: "Vokkaliga" },
  { name: "Namdhari Vokkaliga (ನಾಮಧಾರಿ ಒಕ್ಕಲಿಗ)", category: "Vokkaliga", nigama: "Vokkaliga" },
  { name: "Gangad Kar Vokkaliga (ಗಂಗಡ್ ಕಾರ್ ಒಕ್ಕಲಿಗ)", category: "Vokkaliga", nigama: "Vokkaliga" },
  { name: "Das Vokkaliga (ದಾಸ್ ಒಕ್ಕಲಿಗ)", category: "Vokkaliga", nigama: "Vokkaliga" },
  { name: "Reddy Vokkaliga (ರೆಡ್ಡಿ ಒಕ್ಕಲಿಗ)", category: "Vokkaliga", nigama: "Vokkaliga" },
  { name: "Marasu Vokkaliga (ಮರಸು ಒಕ್ಕಲಿಗ)", category: "Vokkaliga", nigama: "Vokkaliga" },
  { name: "Gowda (ಗೌಡ)", category: "Vokkaliga", nigama: "Vokkaliga" },
  { name: "Hallikar (ಹಳ್ಳಿಕಾರ್)", category: "Vokkaliga", nigama: "Vokkaliga" },
  { name: "Kunchitiga (ಕುಂಚಿಟಿಗ)", category: "Vokkaliga", nigama: "Vokkaliga" },
  { name: "Kaup (ಕಾಪು)", category: "Vokkaliga", nigama: "Vokkaliga" },
  { name: "Heggade (ಹೆಗ್ಗಡೆ)", category: "Vokkaliga", nigama: "Vokkaliga" },
  { name: "Kamma 2 (ಕಮ್ಮ 2)", category: "Vokkaliga", nigama: "Vokkaliga" },
  { name: "Ruddy (ರಡ್ಡಿ)", category: "Vokkaliga", nigama: "Vokkaliga" },
  { name: "Gounder (ಗೌಂಡರ್)", category: "Vokkaliga", nigama: "Vokkaliga" },
  { name: "Namadhari Gowda (ನಾಮಧಾರಿ ಗೌಡ)", category: "Vokkaliga", nigama: "Vokkaliga" },
  { name: "Uppina Kolaga/ Uttama Kolaga (ಉಪ್ಪಿನ ಕೊಳಗ/ಉತ್ತಮ ಕೊಳಗ)", category: "Vokkaliga", nigama: "Vokkaliga" },
  { name: "Veerashaiva Lingayat (ವೀರಶೈವ ಲಿಂಗಾಯತ)", category: "Veerashaiva Lingayata (3B)", nigama: "Veerashaiva Lingayata" },
  { name: "Maratha/Marata (ಮರಾತ/ಮರಾಠ)", category: "Marata", nigama: "Marata" },
  { name: "Are-Kshatriya/Are-Maratha/Aramarata (ಅರೆ ಕ್ಷತ್ರಿ/ಅರೆ ಮರಾಠ/ಅರಮರಾಠ)", category: "Marata", nigama: "Marata" },
  { name: "Arya/Aryaru (ಆರ್ಯ/ಆರ್ಯರು)", category: "Marata", nigama: "Marata" },
  { name: "Konkana Maratha (ಕೊಂಕಣ ಮರಾಠ)", category: "Marata", nigama: "Marata" },
  { name: "Kshatriya Maratha (ಕ್ಷತ್ರಿಯ ಮರಾಠ)", category: "Marata", nigama: "Marata" },
  { name: "Kulwadi (ಕುಳವಾಡಿ)", category: "1", nigama: "Marata" },
];

export const CASTE_NAMES = CASTES.map((c) => c.name);

export const CASTE_CATEGORIES = Array.from(new Set(CASTES.map((c) => c.category))).filter((cat) => cat !== "nan" && cat !== "NaN");

export const NIGAMAS = Array.from(new Set(CASTES.map((c) => c.nigama))).filter((nig) => nig !== "nan" && nig !== "NaN");

